#define COLOR_WHITE         0xFFFFFFFF
#define COLOR_BLACK         0x000000FF
#define COLOR_LIGHTRED      0xFF6347FF
#define COLOR_GRAD1         0xB4B5B7FF
#define COLOR_GRAD2         0xBFC0C2FF
#define COLOR_GRAD3         0xCBCCCEFF
#define COLOR_GRAD4         0xD8D8D8FF
#define COLOR_GRAD5         0xE3E3E3FF
#define COLOR_GRAD6         0xF0F0F0FF
#define COLOR_PURPLE        0xC2A2DAAA
#define COLOR_GREEN         0x0D7304FF
#define COLOR_DARKGREEN     0x33AA33FF
//=======Embed Colors=======
#define EMBED_RED           "{FF0000}"
#define EMBED_WHITE         "{FFFFFF}"
#define EMBED_YELLOW        "{FFFF00}"
#define EMBED_GREEN         "{808040}"
#define EMBED_BLUE          "{0000FF}"
#define EMBED_LIGHTBLUE     "{8080FF}"
#define EMBED_ORANGE        "{FF8000}"
#define EMBED_GREY          "{AFAFAF}"
#define EMBED_CYAN          "{00FFFF}"
#define EMBED_GRAD          "{CBCCCE}"
#define EMBED_GRAD1         "{b4b5b7}"
#define EMBED_PURPLE        "{C68DFF}"
#define EMBED_PINK          "{FF8282}"
#define EMBED_LIGHTBLUE2    "{8D8DFF}"
#define EMBED_LIGHTRED      "{FF6347}"
#define EMBED_DIALOG        "{A8C3E3}"
#define EMBED_LIGHTGREEN    "{AEFFBC}"